### PR TITLE
Symphony 2.5 compatibility

### PR DESCRIPTION
**Pull request by bernardodiasc**
https://github.com/symphonycms/symphony-2/wiki/Migration-Guide-to-2.4-for-Developers#functions and https://github.com/symphonycms/symphony-2/wiki/Migration-Guide-to-2.5-for-Developers#properties

cheers

### CODE REVIEW

**Comment by ahwayakchih** [comment]
Hi, thanks!

It looks good, i would just like to confirm: does it work only with SymphonyCMS 2.5.x, or will it work with 2.4.x too?

I'm asking because changes regarding Time are for 2.4.x, and change regarding Author is for 2.5.x but example from documentation is meant to keep compatibility with 2.4.x. So maybe XML could set compatibility to 2.4.x instead of requiring 2.5.x?
Or we could change Author to 2.5.x only, without additional if/else block?

Thanks again for the patch,
Regards

**Comment by bernardodiasc** [comment]
Yes, I think it is compatible with 2.4 indeed, let me patch the PR.

**Comment by bernardodiasc** [comment]
Hmm, this is not fully tests because I just installed the extension and created a new formatter (to reproduce the errors that I'm sending fixes here). The incompatibility with Sym 2.5 may occour in elsewhere. I'll look further about this, but this is good to merge I think.

**Comment by ahwayakchih** [comment]
OK, thanks!

**Pull request merged**
